### ISSUE TITLE
Error in PropertyPrint component

### ISSUE THREAD

**Issue by szachara** [dockyard/ember-admin#50]
Hi,

I have simple User model without relations and I set up everything as is at GitHub's README page.

I get this error, when I go to **/admin/user** route.
Response from REST server is ok.

Error:
`Uncaught TypeError: undefined is not a function`.

Error occurs in `node_modules/ember-admin/addon/components/property-print.js` at this line:
```javascript
Ember['default'].Handlebars.helpers['bind'].call(context, path, options);
```

Versions: Ember CLI 0.2.3, Ember 1.11.1, Ember Data 1.0.0-beta.16.1.

**Comment by jamiechong** [comment]
I'm receiving the same error:
```
DEBUG: Ember      : 1.12.0-beta.1
DEBUG: Ember Data : 1.0.0-beta.16.1
DEBUG: Firebase   : 2.2.4
DEBUG: EmberFire  : 0.0.0
DEBUG: jQuery     : 1.11.3
```

`Uncaught TypeError: Cannot read property 'call' of undefined on property-print.js:12`

**Comment by szachara** [comment]
I tried master branch and this problem is solved.
