### ISSUE TITLE
Set recordType deprecation

### ISSUE THREAD

**Issue by clairton** [DockYard/ember-admin#59]
In ember-admin#0.1.0 and ember#1.13.11 throws deprecation:
```javascript
DEPRECATION: You attempted to access `recordType` from `(generated model-records controller)`, but object proxying is deprecated. Please use `model.recordType` instead.
```
Anybody have this to?

**Comment by bcardarella** [comment]
I think there were a few more deprecations added to the `1.13.x` in patch releases after ember-data's last release. I can look into this.

**Comment by clairton** [comment]
Thanks!
