### ISSUE TITLE
Assumptions behind expectation of '/admin' routes

### ISSUE THREAD

**Issue by Andrew-Max** [dockyard/ember-admin#62]
I am trying to figure out if we may want to add this to our app and it struck me as odd when I saw the expectation that your api has `/admin` routes. 

This seems to imply a lot about the API you are interacting with, specifically that it should have multiple routes which interact with a single resource (ie a `/model` resource and a `/admin/model` resource which perform crud on the same underlying resource). I have always heard people refer to this as an anti pattern and unRESTful.

So is there some advantage to structuring things this way which I am missing?

**Comment by bcardarella** [comment]
You can customize this https://github.com/dockyard/ember-admin#namespace

**Comment by Andrew-Max** [comment]
Thanks for the quick response!

I might be interpreting this wrong but it seems like regardless of if it is 'admin' or some other arbitrary string there has to be some separate route `{{nameSpace}}/{{modelName}}`'. Is there a way just have it hit the normal route `/{{model}}`. 

Does `namespace` possibly take a `null` value or something like that?

**Comment by bcardarella** [comment]
Yes, you can just set the `namespace` to `undefined`

**Comment by Andrew-Max** [comment]
Thanks!

**Comment by Andrew-Max** [comment]
@bcardarella just for reference `undefined` would blow up for me but `null`.

 Anyway, this is a lot of functionality for very minimal effort. Thanks for the hard work!
