### ISSUE TITLE
Uncaught ReferenceError: adminRouter is not defined

### ISSUE THREAD

**Issue by joog2303** [DockYard/ember-admin#78]
## Version 
Ember 2.6.0
Ember-admin 0.2.1

## Steps to reproduce
After adding the below code to the router.js I get an console errror (noted in title):

Router.map(function() {
  adminRouter(this);
});

**Comment by bcardarella** [comment]
Seems like a duplicate of https://github.com/DockYard/ember-admin/issues/77

Based upon this: https://github.com/DockYard/ember-admin/blob/v0.2.1/tests/dummy/app/router.js#L13 in theory it should be working as the dummy app is consuming the addon for that version. Are you importing it properly: https://github.com/DockYard/ember-admin/blob/v0.2.1/tests/dummy/app/router.js#L3

**Comment by joog2303** [comment]
Thanks! I did not have it imported properly

Fix - import adminRouter from 'ember-admin/router';
